[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/rust.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/vim-quickrun.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'

[[plugins]]
repo = 'preservim/nerdtree'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'junegunn/fzf'
build_on = './install -all'

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''
hook_add = 'source ~/dotfiles/.config/nvim/plugins/cocnvim.vim'

[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']
hook_add = 'source ~/dotfiles/.config/nvim/plugins/flake8.vim'

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']
hook_add = 'source ~/dotfiles/.config/nvim/plugins/autopepe8.vim'