# General ==========================================================================================
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/nerdtree.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'

# [[plugins]]
# repo = 'itchyny/lightline.vim'
# hook_add = 'source ~/dotfiles/.config/nvim/plugins/lightline.vim'

[[plugins]]
repo = 'popkirby/lightline-iceberg'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/vim-quickrun.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-scripts/vim-auto-save'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''
hook_add = 'source ~/dotfiles/.config/nvim/plugins/cocnvim.vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# Language settings ================================================================================
[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/rust.vim'

[[plugins]]
repo = 'racer-rust/vim-racer'