# ==============================================================================
# General settings
# ==============================================================================
# plugin manager
[[plugins]]
repo = 'Shougo/dein.vim'
# An ecosystem of Vim/Neovim which allows developers to write plugins in Deno
[[plugins]]
repo = 'vim-denops/denops.vim'
# Dark deno-powered UI framework for neovim/Vim8
[[plugins]]
repo = 'Shougo/ddu.vim'
source = 'source ~/dotfiles/.config/nvim/plugins/ddu.vim'
# File source for ddu.vim =================
# source
[[plugins]]
repo = 'Shougo/ddu-source-file'
# kind
[[plugins]]
repo = 'Shougo/ddu-kind-file'
# colmn
[[plugins]]
repo = 'Shougo/ddu-column-filename'
# =========================================
# File listing UI for ddu.vim
[[plugins]]
repo = 'Shougo/ddu-ui-filer'
# show directory structure
[[plugins]]
repo = 'preservim/nerdtree'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/nerdtree.vim'
# iceberg theme for vim
[[plugins]]
repo = 'cocopon/iceberg.vim'
# decorate status line
[[plugins]]
repo = 'nvim-lualine/lualine.nvim'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/lualine.vim'
# Graphical icons for nvim in lua
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
# run commands in nvim
[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/vim-quickrun.vim'
# show indent levels
[[plugins]]
repo = 'Yggdroot/indentLine'
# switch between commmentout and uncomment
[[plugins]]
repo = 'tomtom/tcomment_vim'
# auto save on normal mode
[[plugins]]
repo = 'vim-scripts/vim-auto-save'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/vim-auto-save.vim'
# auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'
# fzf like plugin for nvim in llua
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
# ==============================================================================
# Language settings
# ==============================================================================
# lsp manager
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''
hook_add = 'source ~/dotfiles/.config/nvim/plugins/cocnvim.vim'
# auto close tags in html, xml...
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/closetag.vim'
# supoprt for rust
[[plugins]]
repo = 'rust-lang/rust.vim'
hook_add = 'source ~/dotfiles/.config/nvim/plugins/rust.vim'
# plugin for lua
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
